services:
  redis:
    platform: linux/amd64
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  node:
    platform: linux/amd64
    container_name: api-site-de-eventos
    build: src/.
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - redis
    env_file:
      - .env

    volumes:
      - .:/app
